title: My Blog
author: Fady Kuzman
email: f.s.a.kuzman@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Obviously, I will use this page to write about myself and my struggles in life.
  So feel free to criticise and give advice.
  Also People who like to suggest better writing techniques, Grammer and vocabulary
  corrections are more than welcome.
  Have fun. 
  
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
